name: Docker Prod Image CI

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Env variables
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag pepdabass/my-awesome-app-jbp:latest

      - name: Add "date-stamp" tag to the image
        run: docker image tag pepdabass/my-awesome-app-jbp:latest pepdabass/my-awesome-app-jbp:${{env.date-stamp}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Push Docker Image to Docker Hub
        run: docker push --all-tags pepdabass/my-awesome-app-jbp
