name: Docker Test Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose on dev files
        run: docker-compose -f "docker-compose-dev.yml" up -d --build my-awesome-app-jbp-test
